validateProject/validateProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('verifyApp.urls')),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

validateProject/verifyApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('update/<str:pk>/', views.update, name='update'),
    path('reg/', views.reg, name='reg'),
    path('log/', views.log, name='log'),
    path('', views.log_out, name='logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

validateProject/verifyApp/models.py
from django.db import models
from django.contrib.auth.models import User


class infoUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    profile_picture = models.ImageField(
        upload_to='profile_picture', default='profile_picture/def.jpg')

    def __str__(self):
        return self.name

validateProject/verifyApp/forms.py
from django import forms
from .models import infoUser
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username',  'email', 'password')


class infoUserForm(forms.ModelForm):
    class Meta():
        model = infoUser
        fields = ('name', 'profile_picture')


class infoUserUpdateForm(forms.ModelForm):
    class Meta():
        model = infoUser
        fields = ("name", "profile_picture")

    def save(self, commit=True):
        info_user = self.instance
        info_user.name = self.cleaned_data['name']

        if self.cleaned_data['profile_picture']:
            info_user.profile_picture = self.cleaned_data['profile_picture']

        if commit:
            info_user.save()

        return info_user

validateProject/verifyApp/views.py
from django.shortcuts import render, redirect
from .models import User, infoUser
from .forms import infoUserForm, UserForm, infoUserUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy


def home(request):
    registered = False
    context = {'registered': registered}
    return render(request, 'base.html', context)


@login_required(login_url='log')
def index(request):
    registered = True

    current_user = request.user
    current_user_info = infoUser.objects.get(user_id=current_user.id)

    context = {'registered': registered, 'current_user': current_user,
               'current_user_info': current_user_info}
    return render(request, 'index.html', context)


def reg(request):

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_info_form = infoUserForm(request.POST, request.FILES)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user
            user_info.save()

            return redirect('index')

        else:
            registered = False
            context = {'registered': registered,
                       'user_form.errors': user_form.errors, 'user_info_form.errors': user_info_form.errors}
            return render(request, 'base.html', context)
    else:

        user_form = UserForm()
        user_info_form = infoUserForm()

        registered = False
        context = {'user_form': user_form,
                   'user_info_form': user_info_form, 'registered': registered}

        return render(request, 'reg.html', context)


def log(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect('index')

        else:
            return redirect('log')

    return render(request, 'login.html')


@login_required
def log_out(request):
    logout(request)
    registered = False
    context = {'registered': registered}
    return render(request, 'base.html', context)


def update(request, pk):

    Object = infoUser.objects.get(user_id=pk)
    user_info_form = infoUserUpdateForm(instance=Object)

    if request.POST:
        form = infoUserUpdateForm(
            request.POST, request.FILES, instance=Object)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()

            user_info_form = obj

            return redirect('index')

    form = infoUserUpdateForm(
        instance=Object
    )

    context = {'form': form, 'Object': Object}
    return render(request, 'update.html', context)

validateProject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>WELCOME</h1>

    {% if registered %}

    <h1>Hello, Welcome {{user.username}} </h1> <br>
    <h1> {{ user.id }} </h1>
    <a href="{% url 'logout' %}">Logout</a>

    {% else %}

    <a href="{% url 'reg' %}">Register</a> <br>
    <a href="{% url 'log' %}">Login</a> <br>
    <a href="{% url 'reset_password' %}">Forgot Password?</a>

    {% endif %}
</body>

</html>

validateProject/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>WELCOME</h1>

    <h1> {{ current_user.id }} </h1>
    <h1> {{ current_user.username }} </h1>
    <h1> {{ current_user.email }} </h1>
    <h1> {{ current_user_info.name }} </h1>
    <a href="{% url 'update' current_user.id %}">Update</a>
</body>

</html>

validateProject/templates/login.html
<h1>Login</h1>

<form action="" method="POST">

    {% csrf_token %}
    Usename = <input type="text" name="username">
    Password = <input type="password" name="password">

    <button type="submit">Submit</button>
</form>

validateProject/templates/password_reset.html
<h1>Password RESET</h1>

<form method="post">

    {% csrf_token %}
    {{form}}
    <input type="Submit" name="Send email">
</form>

validateProject/templates/password_reset_complete.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

validateProject/templates/password_reset_sent.html
<h1>Password reset sent</h1>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should
    receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam
    folder.</p>

validateProject/templates/reg.html
<h1>Register</h1>

<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    {{user_info_form.as_p}}
    {{user_form.as_p}}

    <input type="submit" value="Submit">

</form>

validateProject/templates/reset_confirm.html
<h1>Enter new password</h1>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

    {% csrf_token %}
    {{form}}
    <input type="Submit" name="Update Password">

</form>

validateProject/templates/update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>UPDATE</h1>

    <form action="" method="POST">

        {% csrf_token %}


        <tr>
            <th><label for="id_name">Name:</label></th>
            {{ form.name }}
            <br>
        </tr>

        {{ Object.profile_picture.url }}
        <tr>
            <th><label for="id_profile_picture">Profile picture:</label></th> <br>
            <td>Currently: <img src="{{ Object.profile_picture.url }}" style="height: 100px; width: 10%;" alt=""> <br>
                Change:
                <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture">
            </td>
        </tr>
        <br>

        <input type="submit" value="Update">

    </form>

    {{ form }}

</body>

</html>